<?php
include_once('web/common/header.php');
include_once('web/common/menu.php');
include_once('web/uke/main/slide.php');
include_once('web/uke/main/introduce.php');
include_once('web/uke/main/thenews.php');
include_once('web/uke/main/main_videw.php');
include_once('web/common/footer.php');
?>